# https://travis-ci.org/spyder-ide/spyder-unittest

language: c

sudo: false

branches:
  only:
    - master

os:
  - linux

env:
  global:
    # Used by qthelpers to close widgets after a defined time
    - TEST_CI="True"
    - TEST_CI_APP="True"
    # Environment variables used by astropy helpers
    - CONDA_DEPENDENCIES="lxml mock nose pytest spyder"
    - PIP_DEPENDENCIES="coveralls pytest-qt"

  matrix:
    # PyQt5
    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt5 PYTEST_QT_API=pyqt5
    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt5 PYTEST_QT_API=pyqt5
    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt5 PYTEST_QT_API=pyqt5
    # PySide2
#    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PySide2 PYTEST_QT_API=pyside2
#    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PySide2 PYTEST_QT_API=pyside2
#    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PySide2 PYTEST_QT_API=pyside2
    # PyQt4
    - TRAVIS_PYTHON_VERSION=3.5 USE_QT_API=PyQt4 PYTEST_QT_API=pyqt4v2
    - TRAVIS_PYTHON_VERSION=3.4 USE_QT_API=PyQt4 PYTEST_QT_API=pyqt4v2
    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PyQt4 PYTEST_QT_API=pyqt4v2
    # PySide
#    - TRAVIS_PYTHON_VERSION=2.7 USE_QT_API=PySide PYTEST_QT_API=pyside

before_install:
  # Test environments for different Qt bindings
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then
      export CONDA_DEPENDENCIES='qt=5.* pyqt=5.* '$CONDA_DEPENDENCIES;
    elif [[ "$USE_QT_API" == "PySide2" ]]; then
      export CONDA_DEPENDENCIES='qt=5.* pyside2 '$CONDA_DEPENDENCIES;
    elif [[ "$USE_QT_API" == "PyQt4" ]]; then
      export CONDA_DEPENDENCIES='qt=4.* pyqt=4.* '$CONDA_DEPENDENCIES;
    elif [[ "$USE_QT_API" == "PySide" ]]; then
      export CONDA_DEPENDENCIES='qt=4.* pyside '$CONDA_DEPENDENCIES;
    fi

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - $CONDA_INSTALL ciocheck -c conda-forge
  - python setup.py develop
  - spyder --reset
  - spyder

script:
  - ciocheck spyder_unittest --disable-tests
  - py.test spyder_unittest --cov=spyder_unittest
