# https://ci.appveyor.com/project/goanpeca/spyder-unittest

matrix:
  fast_finish: true

branches:
  only:
    - master 

environment:
  global:
    # Used by qthelpers to close widgets after a defined time
    TEST_CI: True
    TEST_CI_APP: True
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                      # of 32 bit and 64 bit builds are needed, move this
                      # to the matrix section.
    CONDA_DEPENDENCIES: "lxml mock nose pytest spyder"
    PIP_DEPENDENCIES_2: "coveralls pytest-qt"  # Fix when fixed upstream

  matrix:
    # PyQt5
    - PYTHON_VERSION: "3.6"
      USE_QT_API: "PyQt5"
      PYTEST_QT_API: "pyqt5"
    - PYTHON_VERSION: "2.7"
      USE_QT_API: "PyQt5"
      PYTEST_QT_API: "pyqt5"

platform:
  -x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  # Install pip dependencies.
  - "pip install %PIP_DEPENDENCIES_2%"
  # Install the selected Qt version
  - if "%USE_QT_API%" == "PyQt5" conda install qt=5.* pyqt=5.*
  - if "%USE_QT_API%" == "PySide2" conda install qt=5.* pyside2
  - if "%USE_QT_API%" == "PyQt4" conda install qt=4.* pyqt=4.*
  - if "%USE_QT_API%" == "PySide" conda install qt=4.* pyside
  - "conda install ciocheck -c spyder-ide"
  - "python setup.py develop"
  - "spyder --reset"
  - "spyder"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - ciocheck spyder_unittest --disable-tests
  - conda remove pytest-xdist
  - py.test spyder_unittest --cov=spyder_unittest
